plugins {
    id 'java'
    id 'jacoco'
    id 'application'
}

group = 'ru.nsu.kurumun.expressions'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}
dependencies {
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

test {
    useJUnitPlatform()
    finalizedBy jacocoTestReport
}

jacocoTestReport {
    dependsOn test

    reports {
        xml.required = true
    }

}
application {
    mainClass = 'ru.nsu.kurumun.expressions.Main'
}

tasks.named('run', JavaExec) {
    standardInput = System.in
}
